services:
  - type: cron
    name: taixiu-analyzer
    env: python
    schedule: "*/5 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python auto_taixiu.py"
    plan: free
